export const MOCK_ALL_PRODUCTOS = [
  {
    descripcionProducto: 'Old Prince Puppies Small x 7.5kg',
    costo: 4250,
    ganancia: 1070,
    precio: 5320,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Old Prince Puppies Small x 3kg',
    costo: 2200,
    ganancia: 850,
    precio: 3050,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Old Prince Puppies Med y Grd x 15kg',
    costo: 7500,
    ganancia: 1880,
    precio: 9380,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Old Prince Puppies Med y Grd x 7.5kg',
    costo: 4100,
    ganancia: 1030,
    precio: 5130,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Old Prince Puppies Med y Grd x 3kg',
    costo: 2050,
    ganancia: 850,
    precio: 2900,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Old Prince Adulto Small x 15kg',
    costo: 7500,
    ganancia: 1880,
    precio: 9380,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Old Prince Adulto Small x 7,5kg',
    costo: 4100,
    ganancia: 1030,
    precio: 5130,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Old Prince Adulto Small x 3kg',
    costo: 2050,
    ganancia: 850,
    precio: 2900,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Old Prince Adulto Med y Grd x 20kg',
    costo: 8500,
    ganancia: 2130,
    precio: 10630,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Old Prince Adulto Med y Grd x 15kg',
    costo: 6650,
    ganancia: 1670,
    precio: 8320,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Old Prince Adulto Med y Grd x 7.5kg',
    costo: 3850,
    ganancia: 970,
    precio: 4820,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Old Prince Adulto Med y Grd x 3kg',
    costo: 1900,
    ganancia: 850,
    precio: 2750,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Old Prince NOVEL Cor y Arroz M/G x 15kg',
    costo: 10500,
    ganancia: 2630,
    precio: 13130,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Old Prince NOVEL Cor y Arroz M/G x 7,5kg',
    costo: 5000,
    ganancia: 1250,
    precio: 6250,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Old Prince NOVEL Cor y Arroz M/G x 3kg',
    costo: 2500,
    ganancia: 850,
    precio: 3350,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Old Prince NOVEL Cor y Arroz Adulto Small x 15kg',
    costo: 11400,
    ganancia: 2850,
    precio: 14250,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Old Prince NOVEL Cor y Arroz Adulto Small x 7,5kg',
    costo: 5500,
    ganancia: 1380,
    precio: 6880,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Old Prince NOVEL Cor y Arroz adulto Small x 3kg',
    costo: 2750,
    ganancia: 850,
    precio: 3600,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Old Prince NOVEL Cor y Arroz Puppy x 15kg',
    costo: 11400,
    ganancia: 2850,
    precio: 14250,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Old Prince NOVEL Cor y Arroz Puppy x 7,5kg',
    costo: 5500,
    ganancia: 1380,
    precio: 6880,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Old Prince NOVEL cor y arroz Senior x 15kg',
    costo: 11100,
    ganancia: 2780,
    precio: 13880,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Old Prince Kitten x 7.5kg',
    costo: 6650,
    ganancia: 1670,
    precio: 8320,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Old Prince Kitten x 1kg',
    costo: 1200,
    ganancia: 850,
    precio: 2050,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Old Prince Adulto x 7.5kg',
    costo: 6050,
    ganancia: 1520,
    precio: 7570,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Old Prince Adulto x 3kg',
    costo: 2920,
    ganancia: 850,
    precio: 3770,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Old Prince Urinary x 7.5kg',
    costo: 6900,
    ganancia: 1730,
    precio: 8630,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Old Prince Urinary x 3kg',
    costo: 3350,
    ganancia: 850,
    precio: 4200,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Old Prince Indoor x 7.5kg',
    costo: 6650,
    ganancia: 1670,
    precio: 8320,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Old Prince Indoor x 3kg',
    costo: 3200,
    ganancia: 850,
    precio: 4050,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Old Prince NOVEL Cor y Arroz Kitten x 1kg',
    costo: 1570,
    ganancia: 850,
    precio: 2420,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Old Prince NOVEL Cor y Arroz Kitten x 3kg',
    costo: 4300,
    ganancia: 1080,
    precio: 5380,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Old Prince NOVEL Cor y Arroz Adulto x 1kg',
    costo: 1430,
    ganancia: 850,
    precio: 2280,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Old Prince NOVEL Cor y Arroz Adulto x 3kg',
    costo: 3400,
    ganancia: 850,
    precio: 4250,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Old Prince NOVEL Cor y Arroz Adulto x 7,5kg',
    costo: 7800,
    ganancia: 1950,
    precio: 9750,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Old Prince NOVEL Cor y Arroz Sterilized x 1kg',
    costo: 1570,
    ganancia: 850,
    precio: 2420,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Old Prince NOVEL Cor y Arroz Sterilized x 3kg',
    costo: 4300,
    ganancia: 1080,
    precio: 5380,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Old Prince NOVEL Cor y Arroz Sterilized x 7,5kg',
    costo: 8500,
    ganancia: 2130,
    precio: 10630,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Old Prince Premium gato adulto x 7,5kg',
    costo: 4250,
    ganancia: 1070,
    precio: 5320,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Old Prince Premiun gatito x 7,5kg',
    costo: 4700,
    ganancia: 1180,
    precio: 5880,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Old Prince NOVEL cor y arroz Senior x 3kg',
    costo: 2630,
    ganancia: 850,
    precio: 3480,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Old Prince NOVEL cor y arroz Light x 15kg',
    costo: 11100,
    ganancia: 2780,
    precio: 13880,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Old Prince NOVEL cor y arroz Light x 3kg',
    costo: 2630,
    ganancia: 850,
    precio: 3480,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Old Prince NOVEL Cor y Arroz Puppy x3kg',
    costo: 2630,
    ganancia: 850,
    precio: 3480,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Old Prince NOVEL Cerdo x 15kg',
    costo: 9100,
    ganancia: 2280,
    precio: 11380,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Old Prince NOVEL Cerdo x 3kg',
    costo: 2200,
    ganancia: 850,
    precio: 3050,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Old Prince Weight Control x 15Kg',
    costo: 8900,
    ganancia: 2230,
    precio: 11130,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Old Prince Premium ADx 20kg',
    costo: 6500,
    ganancia: 1630,
    precio: 8130,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Old Prince Premium ADx 3kg',
    costo: 1210,
    ganancia: 850,
    precio: 2060,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Old Prince Premium Cachorro x 15kg',
    costo: 5260,
    ganancia: 1320,
    precio: 6580,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Old Prince Premium Cachorro x 3kg',
    costo: 1330,
    ganancia: 850,
    precio: 2180,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Old Prince Premium Cordero 15kg',
    costo: 7100,
    ganancia: 1780,
    precio: 8880,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Old Prince Premium Cordero 3kg',
    costo: 1780,
    ganancia: 850,
    precio: 2630,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Fawna Cachorro Raza Pequeña x7,5kg',
    costo: 7480,
    ganancia: 1870,
    precio: 9350,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Fawna Cachorro Raza Pequeña x3kg',
    costo: 3850,
    ganancia: 970,
    precio: 4820,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Fawna Cachorro Raza Med/Gran x15kg',
    costo: 13400,
    ganancia: 3350,
    precio: 16750,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Fawna Cachorro Raza Med/Gran x7,5kg',
    costo: 7600,
    ganancia: 1900,
    precio: 9500,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Fawna Cachorro Raza Med/Gran x3kg',
    costo: 3850,
    ganancia: 970,
    precio: 4820,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Fawna Adulto Raza Pequeña x7,5kg',
    costo: 7400,
    ganancia: 1850,
    precio: 9250,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Fawna Adulto Raza Pequeña x3kg',
    costo: 3650,
    ganancia: 920,
    precio: 4570,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Fawna Adulto Raza Med/Gran x3kg',
    costo: 3300,
    ganancia: 850,
    precio: 4150,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Fawna Adulto Raza Med/Gran x15kg',
    costo: 12500,
    ganancia: 3130,
    precio: 15630,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Fawna Light x15kg',
    costo: 11350,
    ganancia: 2840,
    precio: 14190,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Fawna Light x3kg',
    costo: 3750,
    ganancia: 940,
    precio: 4690,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Fawna Senior x15kg',
    costo: 10300,
    ganancia: 2580,
    precio: 12880,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Fawna Senior x3kg',
    costo: 3400,
    ganancia: 850,
    precio: 4250,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Fawna Kitten x1kg',
    costo: 1700,
    ganancia: 850,
    precio: 2550,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Fawna Kitten x3kg',
    costo: 4900,
    ganancia: 1230,
    precio: 6130,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Fawna Gato Adulto x3kg',
    costo: 4800,
    ganancia: 1200,
    precio: 6000,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Fawna Gato Adulto x7,5kg',
    costo: 8900,
    ganancia: 2230,
    precio: 11130,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Fawna Gato Sterilizado x3kg',
    costo: 5250,
    ganancia: 1320,
    precio: 6570,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Fawna Gato Sterilizado x7,5kg',
    costo: 9550,
    ganancia: 2390,
    precio: 11940,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Fawna Gato Urinary x3kg',
    costo: 5700,
    ganancia: 1430,
    precio: 7130,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Fawna Gato Urinary x7,5kg',
    costo: 10300,
    ganancia: 2580,
    precio: 12880,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Origen by Company x 20kg',
    costo: 4100,
    ganancia: 1030,
    precio: 5130,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Company Cachorro x 20kg',
    costo: 5550,
    ganancia: 1390,
    precio: 6940,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Company Adulto x 20kg',
    costo: 5050,
    ganancia: 1270,
    precio: 6320,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Company Gato Adulto x 15kg',
    costo: 6700,
    ganancia: 1680,
    precio: 8380,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Company Gato Adulto x 3kg',
    costo: 1700,
    ganancia: 850,
    precio: 2550,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Company Gatito x 3kg',
    costo: 1830,
    ganancia: 850,
    precio: 2680,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Kongo Natural Cachorro x 21kg',
    costo: 5950,
    ganancia: 1490,
    precio: 7440,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Kongo Natural Cachorro x 15kg',
    costo: 4450,
    ganancia: 1120,
    precio: 5570,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Kongo Natural Cachorro x 8kg',
    costo: 2500,
    ganancia: 850,
    precio: 3350,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Kongo Natural Cachorro x 3 kg',
    costo: 1150,
    ganancia: 850,
    precio: 2000,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Kongo Natural Cachorro x 1.5 kg',
    costo: 600000,
    ganancia: 150000,
    precio: 750000,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Kongo Adulto Raza Pequeña x 15kg',
    costo: 4000,
    ganancia: 1000,
    precio: 5000,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Kongo Adulto Raza Pequeña x 8kg',
    costo: 2200,
    ganancia: 850,
    precio: 3050,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Kongo Adulto Raza Pequeña x 3kg',
    costo: 1050,
    ganancia: 850,
    precio: 1900,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Kongo Adulto Raza Pequeña x 1.5kg',
    costo: 550000,
    ganancia: 137500,
    precio: 687500,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Kongo Natural Adulto M/G x 21kg',
    costo: 5100,
    ganancia: 1280,
    precio: 6380,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Kongo Natural Adulto M/G x 15kg',
    costo: 3800,
    ganancia: 950,
    precio: 4750,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Kongo Natural Adulto M/G x 8kg',
    costo: 2130,
    ganancia: 850,
    precio: 2980,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Kongo Natural Adulto M/G x 3kg',
    costo: 1000,
    ganancia: 850,
    precio: 1850,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Kongo Natural Adulto M/G x 1.5kg',
    costo: 520000,
    ganancia: 130000,
    precio: 650000,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Kongo Natural Gatitos x 8kg',
    costo: 3550,
    ganancia: 890,
    precio: 4440,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Kongo Natural Gatitos x 3kg',
    costo: 1700,
    ganancia: 850,
    precio: 2550,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Kongo Natural Gatitos x 1kg',
    costo: 610000,
    ganancia: 152500,
    precio: 762500,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Kongo Natural Gato adulto x 15kg (C / P)',
    costo: 5800,
    ganancia: 1450,
    precio: 7250,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Kongo Natural Gato Adulto x 8kg (C / P)',
    costo: 3250,
    ganancia: 850,
    precio: 4100,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Kongo Natural Gato Adulto x 3kg (C / P)',
    costo: 1550,
    ganancia: 850,
    precio: 2400,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Kongo Natural Gato Adulto x 1kg (C / P)',
    costo: 560000,
    ganancia: 140000,
    precio: 700000,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Kongo Natural Gato adutlo x 500gr (C / P)',
    costo: 300000,
    ganancia: 75000,
    precio: 375000,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Kongo Gold Natural Cachorro x 21kg',
    costo: 8000,
    ganancia: 2000,
    precio: 10000,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Kongo Gold Natural Cachorro x 15kg',
    costo: 5900,
    ganancia: 1480,
    precio: 7380,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Kongo Gold Natural Cachorro x 8kg',
    costo: 3300,
    ganancia: 850,
    precio: 4150,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Kongo Gold Natural Cachorro x 3kg',
    costo: 1650,
    ganancia: 850,
    precio: 2500,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Kongo Gold Natural Adulto M/G x 21 kg',
    costo: 7350,
    ganancia: 1840,
    precio: 9190,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Kongo Gold Natural Adulto M/G x 15kg',
    costo: 5500,
    ganancia: 1380,
    precio: 6880,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Kongo Gold Natural Adulto M/G x 8kg',
    costo: 3080,
    ganancia: 850,
    precio: 3930,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Kongo Gold Natural Adulto M/G x 3kg',
    costo: 1430,
    ganancia: 850,
    precio: 2280,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Kongo Gold Natural Adulto Raza Peq x 15kg',
    costo: 5750,
    ganancia: 1440,
    precio: 7190,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Kongo Gold Natural Adulto Raza Peq x 3kg',
    costo: 1360,
    ganancia: 850,
    precio: 2210,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Natural Meat Cachorro x 15kg',
    costo: 5850,
    ganancia: 1470,
    precio: 7320,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Natural Meat Cachorro x 7kg',
    costo: 3540,
    ganancia: 890,
    precio: 4430,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Natural Meat Cachorro x 1kg',
    costo: 650000,
    ganancia: 162500,
    precio: 812500,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Natural Meat Adulto x 15kg',
    costo: 5300,
    ganancia: 1330,
    precio: 6630,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Natural Meat Adulto x 7kg',
    costo: 3250,
    ganancia: 850,
    precio: 4100,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Natural Meat Adulto x 1kg',
    costo: 595000,
    ganancia: 148750,
    precio: 743750,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Maintenance Criadores Cachorro x 15kg',
    costo: 3600,
    ganancia: 900,
    precio: 4500,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Maintenance Criadores Cachorro x 3kg',
    costo: 950000,
    ganancia: 237500,
    precio: 1187500,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Maintenance Criadores Adulto x 22kg',
    costo: 4500,
    ganancia: 1130,
    precio: 5630,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Maintenance Criadores Adulto x 15kg',
    costo: 3050,
    ganancia: 850,
    precio: 3900,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Maintenance Criadores Adulto x 3kg',
    costo: 810000,
    ganancia: 202500,
    precio: 1012500,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Maintenance Criadores High Pro x 22kg',
    costo: 5700,
    ganancia: 1430,
    precio: 7130,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Maintenance criadores r. pequeña x 15kg',
    costo: 3200,
    ganancia: 850,
    precio: 4050,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Maintenance Criadores GATO x 15kg',
    costo: 4850,
    ganancia: 1220,
    precio: 6070,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Waffen Criadores x 22kg',
    costo: 9200,
    ganancia: 2300,
    precio: 11500,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Waffen Criadores x 3kg',
    costo: 1590,
    ganancia: 850,
    precio: 2440,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Dr Romero Cachorro x 15kg',
    costo: 4600,
    ganancia: 1150,
    precio: 5750,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Dr Romero Cachorro x 2.7kg',
    costo: 1150,
    ganancia: 850,
    precio: 2000,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Dr Romero Adulto x 15kg',
    costo: 3700,
    ganancia: 930,
    precio: 4630,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Dr Romero Adulto x 2.7kg',
    costo: 870000,
    ganancia: 217500,
    precio: 1087500,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Caudillo Gato x 10kg',
    costo: 2650,
    ganancia: 850,
    precio: 3500,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Caudillo Perro Adulto x 18kg',
    costo: 2700,
    ganancia: 850,
    precio: 3550,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Gaucho Gato x10kg',
    costo: 2750,
    ganancia: 850,
    precio: 3600,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Gaucho Perro x25kg',
    costo: 3400,
    ganancia: 850,
    precio: 4250,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Carnix Adulto x 18kg',
    costo: 2750,
    ganancia: 850,
    precio: 3600,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Cereales Adulto x 18kg',
    costo: 2420,
    ganancia: 850,
    precio: 3270,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Cereales Adulto x 8kg',
    costo: 1240,
    ganancia: 850,
    precio: 2090,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Voraz Junior x 20kg',
    costo: 4550,
    ganancia: 1140,
    precio: 5690,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Voraz Junior x 15kg',
    costo: 3550,
    ganancia: 890,
    precio: 4440,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Voraz Junior x 10kg',
    costo: 2350,
    ganancia: 850,
    precio: 3200,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Voraz Junior x 3kg',
    costo: 890000,
    ganancia: 222500,
    precio: 1112500,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Voraz Adulto x 20kg (MIX,POLLO,CARNE)',
    costo: 3300,
    ganancia: 850,
    precio: 4150,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Voraz Adulto x 15kg (MIX,POLLO,CARNE)',
    costo: 2550,
    ganancia: 850,
    precio: 3400,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Voraz Adulto x 10kg (MIX,POLLO,CARNE)',
    costo: 1750,
    ganancia: 850,
    precio: 2600,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Voraz Adulto x 3kg (MIX,POLLO,CARNE)',
    costo: 650000,
    ganancia: 162500,
    precio: 812500,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Voraz Gatitos x 15kg',
    costo: 5050,
    ganancia: 1270,
    precio: 6320,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Voraz Gatitos x 1kg',
    costo: 520000,
    ganancia: 130000,
    precio: 650000,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Voraz Gatitos x 500 grs',
    costo: 275000,
    ganancia: 68750,
    precio: 343750,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Voraz Gato Adulto x 20kg',
    costo: 5750,
    ganancia: 1440,
    precio: 7190,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Voraz Gato Adulto x 10kg',
    costo: 2950,
    ganancia: 850,
    precio: 3800,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Voraz Gato Adulto x 1kg',
    costo: 450000,
    ganancia: 112500,
    precio: 562500,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Voraz Gato Adulto x 500 grs',
    costo: 240000,
    ganancia: 60000,
    precio: 300000,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'VC Balanced Senior Grande x 15kg',
    costo: 8400,
    ganancia: 2100,
    precio: 10500,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'VC Balanced Adulto Gigante x 20kg',
    costo: 10500,
    ganancia: 2630,
    precio: 13130,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'VC Balanced Adulto Grande x 20kg',
    costo: 9500,
    ganancia: 2380,
    precio: 11880,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'VC Balanced Adulto Mediano x 20kg',
    costo: 9500,
    ganancia: 2380,
    precio: 11880,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'VC Balanced Adulto Raza Pequeña x 15kg',
    costo: 8000,
    ganancia: 2000,
    precio: 10000,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'VC Balanced Adulto Raza Pequeña x 7.5kg',
    costo: 4500,
    ganancia: 1130,
    precio: 5630,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'VC Balanced Cachorro Grande x 20kg',
    costo: 11500,
    ganancia: 2880,
    precio: 14380,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'VC Balanced Cachorro Mediano x 20kg',
    costo: 11500,
    ganancia: 2880,
    precio: 14380,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'VC Balanced Cachorro Raza Pequeña x 7.5kg',
    costo: 5450,
    ganancia: 1370,
    precio: 6820,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'VC Balanced Control de peso x 20kg',
    costo: 11500,
    ganancia: 2880,
    precio: 14380,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'VC Balanced Kitten x 7.5kg',
    costo: 7600,
    ganancia: 1900,
    precio: 9500,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'VC Balanced Adulto x 15kg',
    costo: 13200,
    ganancia: 3300,
    precio: 16500,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'VC Balanced Adulto x 7.5kg',
    costo: 6850,
    ganancia: 1720,
    precio: 8570,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'VC Balanced Control de PH x 7.5kg',
    costo: 7750,
    ganancia: 1940,
    precio: 9690,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'VC Balanced Control de peso x 7.5kg',
    costo: 7550,
    ganancia: 1890,
    precio: 9440,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'VC Balanced Gato Senior X 7.5kg',
    costo: 7100,
    ganancia: 1780,
    precio: 8880,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'VC Premium Perro Adulto x 20kg',
    costo: 5550,
    ganancia: 1390,
    precio: 6940,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'VC Premium Gato Adulto x 15kg',
    costo: 8150,
    ganancia: 2040,
    precio: 10190,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'VC Premium Gato Adulto x 7,5kg',
    costo: 4245,
    ganancia: 1065,
    precio: 5310,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'VC Premium Gato Urinary x 7,5kg',
    costo: 4570,
    ganancia: 1150,
    precio: 5720,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'VC Complete Cachorro x 20kg',
    costo: 7600,
    ganancia: 1900,
    precio: 9500,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'VC Complete Cachorro Pequeños x 20kg',
    costo: 7600,
    ganancia: 1900,
    precio: 9500,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'VC Complete Adulto Pequeños x 20kg',
    costo: 7300,
    ganancia: 1830,
    precio: 9130,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'VC Complete Adulto x 20kg',
    costo: 7300,
    ganancia: 1830,
    precio: 9130,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'VC Complete Control de peso x 20kg',
    costo: 7600,
    ganancia: 1900,
    precio: 9500,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'VC Complete Senior x 20kg',
    costo: 7600,
    ganancia: 1900,
    precio: 9500,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'VC Complete Kitten x 15kg',
    costo: 8700,
    ganancia: 2180,
    precio: 10880,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'VC Complete Kitten x 7.5kg',
    costo: 4800,
    ganancia: 1200,
    precio: 6000,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'VC Complete Adulto x 15kg',
    costo: 8300,
    ganancia: 2080,
    precio: 10380,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'VC Complete Gato Senior x 7,5 kg',
    costo: 4750,
    ganancia: 1190,
    precio: 5940,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'VC Complete Control De Peso / Castrado x 7.5kg',
    costo: 4750,
    ganancia: 1190,
    precio: 5940,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Therapy Urinary x 7,5kg',
    costo: 11000,
    ganancia: 2750,
    precio: 13750,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Therapy Obesity Canino x 15kg',
    costo: 14400,
    ganancia: 3600,
    precio: 18000,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Hop Gato Adulto x 15kg',
    costo: 4500,
    ganancia: 1130,
    precio: 5630,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Therapy Gastrointestinal Canino x 10kg',
    costo: 9100,
    ganancia: 2280,
    precio: 11380,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Therapy Renal Canino x 10kg',
    costo: 9500,
    ganancia: 2380,
    precio: 11880,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Therapy Mobility Canino x 15kg',
    costo: 14600,
    ganancia: 3650,
    precio: 18250,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Therapy Hipoalergenico Canino x 10kg',
    costo: 12300,
    ganancia: 3080,
    precio: 15380,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Therapy Cardiaco Canino x 10kg',
    costo: 10800,
    ganancia: 2700,
    precio: 13500,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Pedigree Cachorro x 21kg',
    costo: 9900,
    ganancia: 2480,
    precio: 12380,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Pedigree Adulto x 21kg',
    costo: 9350,
    ganancia: 2340,
    precio: 11690,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Pedigree Mordida Pequeña x 15kg',
    costo: 7100,
    ganancia: 1780,
    precio: 8880,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Pedigree Mordida Pequeña x 8kg',
    costo: 4250,
    ganancia: 1070,
    precio: 5320,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Pedigree Senior x 8kg',
    costo: 3800,
    ganancia: 950,
    precio: 4750,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Pedigree HIGH PRO x21kg',
    costo: 11000,
    ganancia: 2750,
    precio: 13750,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Whiskas Adulto x 10kg ( PESCADO,CARNE,POLLO)',
    costo: 7250,
    ganancia: 1820,
    precio: 9070,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Whiskas Gatitos x 10kg',
    costo: 7250,
    ganancia: 1820,
    precio: 9070,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Provet Light x 15kg',
    costo: 7540,
    ganancia: 1890,
    precio: 9430,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Provet Cachorro x 15 kg',
    costo: 8120,
    ganancia: 2030,
    precio: 10150,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Provet Adulto Alta Performance x 20kg',
    costo: 9405,
    ganancia: 2355,
    precio: 11760,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Provet Adulto Sport x 18kg',
    costo: 7225,
    ganancia: 1815,
    precio: 9040,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Provet Adulto +7 x 15kg',
    costo: 7050,
    ganancia: 1770,
    precio: 8820,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Provet Adulto Mega Skin x 15kg',
    costo: 8250,
    ganancia: 2070,
    precio: 10320,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Provet Adulto Pequeños Alta Performance x 15kg',
    costo: 7730,
    ganancia: 1940,
    precio: 9670,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Total Balance Perro Adulto x 20kg',
    costo: 3800,
    ganancia: 950,
    precio: 4750,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Total Balance Perro Adulto Pequeños x 20kg',
    costo: 4200,
    ganancia: 1050,
    precio: 5250,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Total Balance Perro Adulto ULTRA PRO x 20kg',
    costo: 5070,
    ganancia: 1270,
    precio: 6340,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Total Balance CACHORRO ULTRA PRO x 15kg',
    costo: 3740,
    ganancia: 940,
    precio: 4680,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Pro Plan Puppies Complete x15kg',
    costo: 16130,
    ganancia: 4040,
    precio: 20170,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Pro Plan Puppies Complete x3kg',
    costo: 4960,
    ganancia: 1240,
    precio: 6200,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Pro Plan Puppies Complete x1kg',
    costo: 1853,
    ganancia: 857,
    precio: 2710,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Pro Plan Puppies Small x 7.5kg',
    costo: 9920,
    ganancia: 2480,
    precio: 12400,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Pro Plan Puppies Small x 3kg',
    costo: 4960,
    ganancia: 1240,
    precio: 6200,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Pro Plan Puppies Small x 1kg',
    costo: 1853,
    ganancia: 857,
    precio: 2710,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Pro Plan Kitten x 7.5 kg',
    costo: 15260,
    ganancia: 3820,
    precio: 19080,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Pro Plan Kitten x 3kg',
    costo: 7415,
    ganancia: 1855,
    precio: 9270,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Pro Plan Kitten x 1kg',
    costo: 2670,
    ganancia: 850,
    precio: 3520,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Pro Plan Adulto x 15kg',
    costo: 23240,
    ganancia: 5810,
    precio: 29050,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Pro Plan Adulto x 7.5 kg',
    costo: 13190,
    ganancia: 3300,
    precio: 16490,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Pro Plan Adulto x 3kg',
    costo: 6760,
    ganancia: 1690,
    precio: 8450,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Pro Plan Adulto Complete x 15kg',
    costo: 14600,
    ganancia: 3650,
    precio: 18250,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Pro Plan Adulto Complete x 3kg',
    costo: 4470,
    ganancia: 1120,
    precio: 5590,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Pro Plan Adulto Small x 7.5 kg',
    costo: 8940,
    ganancia: 2240,
    precio: 11180,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Pro Plan Adulto Small x 3kg',
    costo: 4470,
    ganancia: 1120,
    precio: 5590,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Pro Plan Reduce Calorie x 15 kg',
    costo: 16895,
    ganancia: 4225,
    precio: 21120,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Pro Plan Reduce Calorie Small x 7.5kg',
    costo: 11120,
    ganancia: 2780,
    precio: 13900,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Pro Plan Reduce Calorie x 3kg',
    costo: 5450,
    ganancia: 1370,
    precio: 6820,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Pro Plan Reduce Calorie Small x 3kg',
    costo: 5450,
    ganancia: 1370,
    precio: 6820,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Pro Plan Exigent Small x 3kg',
    costo: 5450,
    ganancia: 1370,
    precio: 6820,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Pro Plan Sensitive Skin x15kg',
    costo: 17895,
    ganancia: 4475,
    precio: 22370,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Pro Plan Sensitive Skin x 3kg',
    costo: 5450,
    ganancia: 1370,
    precio: 6820,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Pro Plan Sensitive Skin Small x 7,5kg',
    costo: 11120,
    ganancia: 2780,
    precio: 13900,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Pro Plan Sensitive Skin Small x 3kg',
    costo: 5450,
    ganancia: 1370,
    precio: 6820,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Pro Plan Active Mind x 15kg',
    costo: 16895,
    ganancia: 4225,
    precio: 21120,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Pro Plan Active Mind Small x 7,5kg',
    costo: 10575,
    ganancia: 2645,
    precio: 13220,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Pro Plan Active Mind x 3kg',
    costo: 5230,
    ganancia: 1310,
    precio: 6540,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Pro Plan Active Mind Small x 3kg',
    costo: 5230,
    ganancia: 1310,
    precio: 6540,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Pro Plan Adulto + 7 x 3kg',
    costo: 7520,
    ganancia: 1880,
    precio: 9400,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Pro Plan Adulto + 7 x 7.5kg',
    costo: 14715,
    ganancia: 3685,
    precio: 18400,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Pro Plan Urinary x 15kg',
    costo: 24525,
    ganancia: 6135,
    precio: 30660,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Pro Plan Urinary x 7.5kg',
    costo: 14390,
    ganancia: 3600,
    precio: 17990,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Pro Plan Urinary x 3kg',
    costo: 7740,
    ganancia: 1940,
    precio: 9680,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Pro Plan Urinary x 1kg',
    costo: 2835,
    ganancia: 855,
    precio: 3690,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Pro Plan Sterilized x 7.5 kg',
    costo: 15805,
    ganancia: 3955,
    precio: 19760,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Pro Plan Sterilized x 1kg',
    costo: 2835,
    ganancia: 855,
    precio: 3690,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Pro Plan Reduce Calorie x 7.5 kg',
    costo: 15260,
    ganancia: 3820,
    precio: 19080,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Pro Plan Reduce Calorie x 3kg',
    costo: 7740,
    ganancia: 1940,
    precio: 9680,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Pro Plan Reduce Calorie x 1kg',
    costo: 2835,
    ganancia: 855,
    precio: 3690,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Felix Megamix Gatitos 15kg',
    costo: 10900,
    ganancia: 2730,
    precio: 13630,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Felix Megamix Gato Adulto 15kg',
    costo: 9920,
    ganancia: 2480,
    precio: 12400,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Gati Adulto Pescado x 15kg',
    costo: 6375,
    ganancia: 1595,
    precio: 7970,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Gati Adulto Carne x 15kg',
    costo: 6375,
    ganancia: 1595,
    precio: 7970,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Gati Adulto Salmon x 15kg',
    costo: 6375,
    ganancia: 1595,
    precio: 7970,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Gati Adulto Pollo x 15kg',
    costo: 6375,
    ganancia: 1595,
    precio: 7970,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Excellent Puppies Chiken & Rice x 20kg',
    costo: 12750,
    ganancia: 3190,
    precio: 15940,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Excellent Puppies Chiken & Rice x 15kg',
    costo: 10355,
    ganancia: 2595,
    precio: 12950,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Excellent Puppies Chiken & Rice x 3kg',
    costo: 2890,
    ganancia: 850,
    precio: 3740,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Excellent Adulto Chiken & Rice x 20kg',
    costo: 11230,
    ganancia: 2810,
    precio: 14040,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Excellent Adulto Chiken & Rice x 15kg',
    costo: 9430,
    ganancia: 2360,
    precio: 11790,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Excellent Adulto Chiken & Rice x 3kg',
    costo: 2615,
    ganancia: 855,
    precio: 3470,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Excellent Kitten x7.5kg',
    costo: 9375,
    ganancia: 2345,
    precio: 11720,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Excellent Kitten x 1kg',
    costo: 1690,
    ganancia: 850,
    precio: 2540,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Excellent Adulto Chiken & Rice x 15kg',
    costo: 16350,
    ganancia: 4090,
    precio: 20440,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Excellent Adulto Chiken & Rice x 7.5kg',
    costo: 8450,
    ganancia: 2120,
    precio: 10570,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Excellent Adulto Chiken & Rice x 3kg',
    costo: 4250,
    ganancia: 1070,
    precio: 5320,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Excellent Adulto Chiken & Rice x 1kg',
    costo: 1635,
    ganancia: 855,
    precio: 2490,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Excellent Reduced Calorie x 15kg',
    costo: 10900,
    ganancia: 2730,
    precio: 13630,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Excellent Reduced Calorie x 3kg',
    costo: 3000,
    ganancia: 850,
    precio: 3850,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Excellent Puppies small x 15kg',
    costo: 10355,
    ganancia: 2595,
    precio: 12950,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Excellent Puppies small x 3kg',
    costo: 2878,
    ganancia: 852,
    precio: 3730,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Excellent Adulto small x 15kg',
    costo: 9430,
    ganancia: 2360,
    precio: 11790,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Excellent Adulto Small x 3kg',
    costo: 2615,
    ganancia: 855,
    precio: 3470,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Excellent Adulto +7 Chiken & Rice x 15kg',
    costo: 10355,
    ganancia: 2595,
    precio: 12950,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Excellent Adulto +7 Chiken & Rice x 3kg',
    costo: 2856,
    ganancia: 854,
    precio: 3710,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Excellent Adulto Formula x 20kg',
    costo: 10790,
    ganancia: 2700,
    precio: 13490,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Excellent Puppy Formula x 20kg',
    costo: 12860,
    ganancia: 3220,
    precio: 16080,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Excellent Esterilizado x 7.5kg',
    costo: 9755,
    ganancia: 2445,
    precio: 12200,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Excellent Esterilizado x 1kg',
    costo: 1800,
    ganancia: 850,
    precio: 2650,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Excellent Urinary x 7.5kg',
    costo: 9700,
    ganancia: 2430,
    precio: 12130,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Excellent Urinary x 1kg',
    costo: 1800,
    ganancia: 850,
    precio: 2650,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Dogui Cachorro x 24kg',
    costo: 6965,
    ganancia: 1745,
    precio: 8710,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Dogui Adulto Carne, Cereales y Arroz x 21kg',
    costo: 6345,
    ganancia: 1595,
    precio: 7940,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Dog Chow Cachorro M/G x 21kg',
    costo: 11100,
    ganancia: 2780,
    precio: 13880,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Dog Chow Cachorro Raza Pequeña x 21kg',
    costo: 11100,
    ganancia: 2780,
    precio: 13880,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Dog Chow Cachorro x 3kg',
    costo: 2400,
    ganancia: 850,
    precio: 3250,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Dog Chow Cachorro Pequeños x 3kg',
    costo: 2400,
    ganancia: 850,
    precio: 3250,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Dog Chow Adulto M/G x 21kg',
    costo: 10235,
    ganancia: 2565,
    precio: 12800,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Dog Chow Adulto Raza Pequeña x 21kg',
    costo: 10235,
    ganancia: 2565,
    precio: 12800,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Dog Chow Adulto x 3kg',
    costo: 2235,
    ganancia: 855,
    precio: 3090,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Dog Chow Adulto Raza Peq x 3kg',
    costo: 2235,
    ganancia: 855,
    precio: 3090,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Dog Chow Edad Madura x 21kg',
    costo: 11340,
    ganancia: 2840,
    precio: 14180,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Dog Chow Edad Madura x 3kg',
    costo: 2400,
    ganancia: 850,
    precio: 3250,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Dog Chow Sano y en forma x 21kg',
    costo: 11340,
    ganancia: 2840,
    precio: 14180,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Dog Chow Sano y en forma x 3kg',
    costo: 2400,
    ganancia: 850,
    precio: 3250,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Cat Chow Gatitos x 15kg',
    costo: 12295,
    ganancia: 3075,
    precio: 15370,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Cat Chow Gatitos x 8kg',
    costo: 7130,
    ganancia: 1790,
    precio: 8920,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Cat Chow Gatitos x 1kg',
    costo: 1365,
    ganancia: 855,
    precio: 2220,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Cat Chow Adulto x 15kg PESCADO/CARNE',
    costo: 11390,
    ganancia: 2850,
    precio: 14240,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Cat Chow Adulto x 8kg PESCADO/CARNE',
    costo: 6625,
    ganancia: 1665,
    precio: 8290,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Cat Chow Adulto x 1kg PESCADO/CARNE',
    costo: 1255,
    ganancia: 855,
    precio: 2110,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Cat Chow Esterilizados x 1kg',
    costo: 1470,
    ganancia: 850,
    precio: 2320,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Cat Chow Esterilizados x 15kg',
    costo: 12970,
    ganancia: 3250,
    precio: 16220,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Bonelo (Todos los Tamaños) x 22kg',
    costo: 7260,
    ganancia: 1820,
    precio: 9080,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Mini Started x 1kg',
    costo: 1950,
    ganancia: 850,
    precio: 2800,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Mini Puppy x 3kg',
    costo: 4800,
    ganancia: 1200,
    precio: 6000,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Mini Puppy x 7.5kg',
    costo: 9300,
    ganancia: 2330,
    precio: 11630,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Mini Puppy x 15kg',
    costo: 16500,
    ganancia: 4130,
    precio: 20630,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Mini Adulto x 3kg',
    costo: 4350,
    ganancia: 1090,
    precio: 5440,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Mini Adulto x 7.5kg',
    costo: 9200,
    ganancia: 2300,
    precio: 11500,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Mini Adulto Ageing +8 x 3kg',
    costo: 4650,
    ganancia: 1170,
    precio: 5820,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Mini Adulto Ageing +12 x 3kg',
    costo: 4650,
    ganancia: 1170,
    precio: 5820,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Mini Exigent 3kg',
    costo: 4950,
    ganancia: 1240,
    precio: 6190,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Mini Weight Care x 3kg',
    costo: 4950,
    ganancia: 1240,
    precio: 6190,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Medium Puppy x 15kg',
    costo: 16100,
    ganancia: 4030,
    precio: 20130,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Medium Puppy x 3kg',
    costo: 4700,
    ganancia: 1180,
    precio: 5880,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Medium Adulto x 15kg',
    costo: 14300,
    ganancia: 3580,
    precio: 17880,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Medium Adulto x 7,5kg',
    costo: 8700,
    ganancia: 2180,
    precio: 10880,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Medium Adulto x 3kg',
    costo: 4150,
    ganancia: 1040,
    precio: 5190,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Medium Weight Care x 3kg',
    costo: 4850,
    ganancia: 1220,
    precio: 6070,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Medium Weight Care x 10kg',
    costo: 11200,
    ganancia: 2800,
    precio: 14000,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Medium Ageing +7 x 15kg',
    costo: 15800,
    ganancia: 3950,
    precio: 19750,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Maxi Puppy x 15kg',
    costo: 16100,
    ganancia: 4030,
    precio: 20130,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Maxi Adulto x 15kg',
    costo: 14300,
    ganancia: 3580,
    precio: 17880,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Maxi Ageing +8 x 15kg',
    costo: 15700,
    ganancia: 3930,
    precio: 19630,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Bulldog frances adulto x 3Kg',
    costo: 4850,
    ganancia: 1220,
    precio: 6070,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Bulldog frances Junior x 3Kg',
    costo: 5400,
    ganancia: 1350,
    precio: 6750,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Bulldog frances adulto x 7,5Kg',
    costo: 10000,
    ganancia: 2500,
    precio: 12500,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Dachsund 3kg',
    costo: 4850,
    ganancia: 1220,
    precio: 6070,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Schnauzer 3kg',
    costo: 4850,
    ganancia: 1220,
    precio: 6070,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Yorkshire Junior x 3 kg',
    costo: 5400,
    ganancia: 1350,
    precio: 6750,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Yorkshire adulto x 3 kg',
    costo: 4850,
    ganancia: 1220,
    precio: 6070,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Poodle junior (caniche) x 3Kg',
    costo: 5400,
    ganancia: 1350,
    precio: 6750,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Poodle adulto (caniche) x 3Kg',
    costo: 4850,
    ganancia: 1220,
    precio: 6070,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Poodle adulto (cancihe) x 7,5Kg',
    costo: 10000,
    ganancia: 2500,
    precio: 12500,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Pug Adulto 3kg',
    costo: 4850,
    ganancia: 1220,
    precio: 6070,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Pug Adulto 7,5kg',
    costo: 10000,
    ganancia: 2500,
    precio: 12500,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Pug Junior 3kg',
    costo: 5400,
    ganancia: 1350,
    precio: 6750,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Jack Russell Adulto 3kg',
    costo: 4850,
    ganancia: 1220,
    precio: 6070,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Jack Russell Junior 3kg',
    costo: 5400,
    ganancia: 1350,
    precio: 6750,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Satiety canine x 1,5Kg',
    costo: 2270,
    ganancia: 850,
    precio: 3120,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Satiety canine Small x 1,5Kg',
    costo: 2300,
    ganancia: 850,
    precio: 3150,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Satiety canine x 7,5Kg',
    costo: 9300,
    ganancia: 2330,
    precio: 11630,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Satiety canine x 15Kg',
    costo: 16500,
    ganancia: 4130,
    precio: 20630,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Mobility canine x 2Kg',
    costo: 3400,
    ganancia: 850,
    precio: 4250,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Mobility Canine Large x 10Kg',
    costo: 13700,
    ganancia: 3430,
    precio: 17130,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Gastrointestinal canine junior x 2Kg',
    costo: 3150,
    ganancia: 850,
    precio: 4000,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Gastrointestinal canine x 2Kg',
    costo: 2950,
    ganancia: 850,
    precio: 3800,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Gastrointestinal canine x 10Kg',
    costo: 11700,
    ganancia: 2930,
    precio: 14630,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Diabetic canine x 2Kg',
    costo: 3400,
    ganancia: 850,
    precio: 4250,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Diabetic canine x 10Kg',
    costo: 13700,
    ganancia: 3430,
    precio: 17130,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Cardiac canine x 2Kg',
    costo: 3350,
    ganancia: 850,
    precio: 4200,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Cardiac canine x 10Kg',
    costo: 13700,
    ganancia: 3430,
    precio: 17130,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Hepatic canine x 1,5Kg',
    costo: 2450,
    ganancia: 850,
    precio: 3300,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Hepatic canine x 10Kg',
    costo: 13300,
    ganancia: 3330,
    precio: 16630,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Renal canine x 1,5Kg',
    costo: 2200,
    ganancia: 850,
    precio: 3050,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Renal canine x 10Kg',
    costo: 12000,
    ganancia: 3000,
    precio: 15000,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Hipoalergenico canine x 2Kg',
    costo: 3680,
    ganancia: 920,
    precio: 4600,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Hipoalergenico canine x 10Kg',
    costo: 13800,
    ganancia: 3450,
    precio: 17250,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Hipoalergenico Small x 2Kg',
    costo: 3800,
    ganancia: 950,
    precio: 4750,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Urinary canine S/O x 1,5Kg',
    costo: 2480,
    ganancia: 850,
    precio: 3330,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Urinary canine S/O x 10Kg',
    costo: 13400,
    ganancia: 3350,
    precio: 16750,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Calm Canine 2kg',
    costo: 3500,
    ganancia: 880,
    precio: 4380,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Royal Canin Kitten x 1,5Kg',
    costo: 3890,
    ganancia: 980,
    precio: 4870,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Royal Canin Kitten x 7,5Kg',
    costo: 13500,
    ganancia: 3380,
    precio: 16880,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Royal Canin Fit 32 x 1,5Kg',
    costo: 3400,
    ganancia: 850,
    precio: 4250,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Royal Canin Fit 32 x 7,5Kg',
    costo: 12200,
    ganancia: 3050,
    precio: 15250,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Royal Canin Fit 32 x 15Kg',
    costo: 21700,
    ganancia: 5430,
    precio: 27130,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Persian feline x 7,5Kg',
    costo: 16500,
    ganancia: 4130,
    precio: 20630,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Indoor + 7 feline x 1,5Kg',
    costo: 3550,
    ganancia: 890,
    precio: 4440,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Indoor + 7 feline x 7,5Kg',
    costo: 12800,
    ganancia: 3200,
    precio: 16000,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Indoor Feline x 7,5Kg',
    costo: 12200,
    ganancia: 3050,
    precio: 15250,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Indoor Longhair Feline x 1,5Kg',
    costo: 3400,
    ganancia: 850,
    precio: 4250,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Indoor Feline x 1,5Kg',
    costo: 3400,
    ganancia: 850,
    precio: 4250,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Active + 7 feline x 1,5Kg',
    costo: 3550,
    ganancia: 890,
    precio: 4440,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Sensible feline x 1,5 Kg',
    costo: 3400,
    ganancia: 850,
    precio: 4250,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Hairball feline x 1,5Kg',
    costo: 3900,
    ganancia: 980,
    precio: 4880,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Digestive Care x 1,5Kg',
    costo: 3900,
    ganancia: 980,
    precio: 4880,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Exigent feline x 1,5Kg',
    costo: 3400,
    ganancia: 850,
    precio: 4250,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Gastrointestinal feline x 2Kg',
    costo: 4500,
    ganancia: 1130,
    precio: 5630,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Hipoalergenico feline x 1,5Kg',
    costo: 4050,
    ganancia: 1020,
    precio: 5070,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Renal feline x 2Kg',
    costo: 4100,
    ganancia: 1030,
    precio: 5130,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Castrado weight control feline x 1,5Kg',
    costo: 3300,
    ganancia: 850,
    precio: 4150,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Castrado weight control feline x 3Kg',
    costo: 6450,
    ganancia: 1620,
    precio: 8070,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Castrado weight control feline x 7,5Kg',
    costo: 12300,
    ganancia: 3080,
    precio: 15380,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Hepatic feline x 1,5Kg',
    costo: 3400,
    ganancia: 850,
    precio: 4250,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Satiety feline x 1,5Kg',
    costo: 3250,
    ganancia: 850,
    precio: 4100,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Diabetic feline x 1,5Kg',
    costo: 4150,
    ganancia: 1040,
    precio: 5190,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Calm feline x 2kg',
    costo: 4900,
    ganancia: 1230,
    precio: 6130,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Urinary care feline x 1,5Kg',
    costo: 3900,
    ganancia: 980,
    precio: 4880,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Urinary care feline x 7,5Kg',
    costo: 14000,
    ganancia: 3500,
    precio: 17500,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Urinary S/O feline x 1,5Kg',
    costo: 3600,
    ganancia: 900,
    precio: 4500,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Urinary S/O feline x 7,5Kg',
    costo: 13200,
    ganancia: 3300,
    precio: 16500,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Performance Adulto x 15kg',
    costo: 10600,
    ganancia: 2650,
    precio: 13250,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Performance Adulto x 20kg',
    costo: 13500,
    ganancia: 3380,
    precio: 16880,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Performance Junior x 15kg',
    costo: 11180,
    ganancia: 2800,
    precio: 13980,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Performance Weight Control x 15kg',
    costo: 10600,
    ganancia: 2650,
    precio: 13250,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Performance Kitten x 7.5kg',
    costo: 9700,
    ganancia: 2430,
    precio: 12130,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Performance Adulto x 7.5kg',
    costo: 8700,
    ganancia: 2180,
    precio: 10880,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Premium Adulto x 20kg',
    costo: 11850,
    ganancia: 2970,
    precio: 14820,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Premium Junior x 15kg',
    costo: 10800,
    ganancia: 2700,
    precio: 13500,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Premium Adulto x 10kg',
    costo: 10600,
    ganancia: 2650,
    precio: 13250,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Eukanuba Puppy Small x 3kg',
    costo: 3350,
    ganancia: 850,
    precio: 4200,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Eukanuba Adulto Small x 3kg',
    costo: 3150,
    ganancia: 850,
    precio: 4000,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Eukanuba Weight Control Small x 3kg',
    costo: 3450,
    ganancia: 870,
    precio: 4320,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Eukanuba Senior Small x 3kg',
    costo: 3250,
    ganancia: 850,
    precio: 4100,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Eukanuba Cachorro Small x 15kg',
    costo: 11800,
    ganancia: 2950,
    precio: 14750,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Eukanuba Cachorro Medium x 15kg',
    costo: 11200,
    ganancia: 2800,
    precio: 14000,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Eukanuba Cachorro Large x 15kg',
    costo: 11200,
    ganancia: 2800,
    precio: 14000,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Eukanuba Adulto Small x 15kg',
    costo: 10900,
    ganancia: 2730,
    precio: 13630,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Eukanuba Adulto Medium x 15kg',
    costo: 10600,
    ganancia: 2650,
    precio: 13250,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Eukanuba Adulto Large x 15kg',
    costo: 10600,
    ganancia: 2650,
    precio: 13250,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Eukanuba Senior (LARGE)x 15kg',
    costo: 11100,
    ganancia: 2780,
    precio: 13880,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Eukanuba Weight Control (LARGE) x 15kg',
    costo: 11900,
    ganancia: 2980,
    precio: 14880,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Eukanuba Adulto Small x7,5kg',
    costo: 6600,
    ganancia: 1650,
    precio: 8250,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Eukanuba Premium Performance x 15kg',
    costo: 11200,
    ganancia: 2800,
    precio: 14000,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Iams Perro Adulto x 15kg',
    costo: 10500,
    ganancia: 2630,
    precio: 13130,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Iams Gato Adulto x 15kg',
    costo: 18500,
    ganancia: 4630,
    precio: 23130,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Sieger Senior Raza Pequeña x 12kg',
    costo: 11900,
    ganancia: 2980,
    precio: 14880,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Sieger Cachorro x 15kg',
    costo: 12400,
    ganancia: 3100,
    precio: 15500,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Sieger Adulto Raza Pequeña x 12kg',
    costo: 10200,
    ganancia: 2550,
    precio: 12750,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Sieger Light x 12kg',
    costo: 10000,
    ganancia: 2500,
    precio: 12500,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Sieger Adulto Super Premium x 15kg',
    costo: 11600,
    ganancia: 2900,
    precio: 14500,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Sieger Criadores Adulto x 20kg',
    costo: 11900,
    ganancia: 2980,
    precio: 14880,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Sieger Adulto x 7,5kg',
    costo: 9500,
    ganancia: 2380,
    precio: 11880,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Sieger Kitten x 7,5kg',
    costo: 9500,
    ganancia: 2380,
    precio: 11880,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Sieger Urinary x 7,5kg',
    costo: 9500,
    ganancia: 2380,
    precio: 11880,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Sieger Stress Control x 7,5kg',
    costo: 9500,
    ganancia: 2380,
    precio: 11880,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Sieger Light x 7,5kg',
    costo: 9500,
    ganancia: 2380,
    precio: 11880,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Agility Adulto x 20kg',
    costo: 8000,
    ganancia: 2000,
    precio: 10000,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Agility Adulto R.PEQ x 15kg',
    costo: 7500,
    ganancia: 1880,
    precio: 9380,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Agility Cachorro x 20kg',
    costo: 7800,
    ganancia: 1950,
    precio: 9750,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Agility Adulto x 10kg',
    costo: 7900,
    ganancia: 1980,
    precio: 9880,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Agility Kitten x 10kg',
    costo: 8500,
    ganancia: 2130,
    precio: 10630,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Agility Control Peso x 10kg',
    costo: 8500,
    ganancia: 2130,
    precio: 10630,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Agility Urinary x 10kg',
    costo: 8500,
    ganancia: 2130,
    precio: 10630,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Nutribon Cachorro x 15kg',
    costo: 4136,
    ganancia: 1034,
    precio: 5170,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Nutribon Adulto x 20kg',
    costo: 3993,
    ganancia: 1007,
    precio: 5000,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Nutribon Raza Pequeña x 20kg',
    costo: 5654,
    ganancia: 1416,
    precio: 7070,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Nutribon Raza Pequeña x 8kg',
    costo: 2448,
    ganancia: 852,
    precio: 3300,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Nutribon XQ Cachorro x20kg',
    costo: 7711,
    ganancia: 1929,
    precio: 9640,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Nutribon XQ Adulto x 20kg',
    costo: 6083,
    ganancia: 1527,
    precio: 7610,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Nutribon XQ Raza Pequeña x 8kg',
    costo: 3350,
    ganancia: 850,
    precio: 4200,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Nutribon XQ Control de peso x20kg',
    costo: 7084,
    ganancia: 1776,
    precio: 8860,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Nutribon XQ Control de peso x 8kg',
    costo: 3009,
    ganancia: 851,
    precio: 3860,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Nutribon Adulto x 20kg',
    costo: 6622,
    ganancia: 1658,
    precio: 8280,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Nutribon Adulto x 8kg',
    costo: 2882,
    ganancia: 858,
    precio: 3740,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Nutribon XQ Adulto x 20kg',
    costo: 8338,
    ganancia: 2092,
    precio: 10430,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Nutribon XQ Adulto x 8kg',
    costo: 3702,
    ganancia: 928,
    precio: 4630,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Nutribon XQ Gatito x 8kg',
    costo: 4202,
    ganancia: 1058,
    precio: 5260,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Matute Perro Adulto x 20kg',
    costo: 3190,
    ganancia: 850,
    precio: 4040,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Sabrositos Cachorro x 8kg',
    costo: 2490,
    ganancia: 850,
    precio: 3340,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Sabrositos Cachorro x 18kg',
    costo: 5200,
    ganancia: 1300,
    precio: 6500,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Sabrositos Adulto x 15kg (MIX,VARIEDADES,CERDO)',
    costo: 3350,
    ganancia: 850,
    precio: 4200,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Sabrositos Adulto x 20kg (MIX,VARIEDADES,CERDO)',
    costo: 4560,
    ganancia: 1140,
    precio: 5700,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Sabrositos Gato x 10kg',
    costo: 3480,
    ganancia: 870,
    precio: 4350,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Sabrositos Gato x 20kg',
    costo: 6500,
    ganancia: 1630,
    precio: 8130,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Raza Cachorro x 15kg',
    costo: 4350,
    ganancia: 1090,
    precio: 5440,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Raza Adulto x15kg (MIX,CARNE)',
    costo: 3500,
    ganancia: 880,
    precio: 4380,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Raza Adulto x 21kg (MIX,CARNE)',
    costo: 4750,
    ganancia: 1190,
    precio: 5940,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Raza Reduce calories x15kg',
    costo: 4000,
    ganancia: 1000,
    precio: 5000,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Raza senior x 15kg',
    costo: 4000,
    ganancia: 1000,
    precio: 5000,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Raza Adulto R.PEQ x 15kg',
    costo: 3500,
    ganancia: 880,
    precio: 4380,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Raza gatitos x 8kg',
    costo: 3450,
    ganancia: 870,
    precio: 4320,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Raza Adulto x15kg',
    costo: 4950,
    ganancia: 1240,
    precio: 6190,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Raza Adulto x 10kg (MIX,PESCADO,POLLO)',
    costo: 3480,
    ganancia: 870,
    precio: 4350,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Estampa Perro Adulto Plus x 20kg',
    costo: 6800,
    ganancia: 1700,
    precio: 8500,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Estampa Perro Adulto Tradicional x 20kg',
    costo: 5900,
    ganancia: 1480,
    precio: 7380,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Estampa Gato Adulto x 15kg',
    costo: 5500,
    ganancia: 1380,
    precio: 6880,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Logan Perro Adulto x 20kg',
    costo: 4700,
    ganancia: 1180,
    precio: 5880,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Logan Perro Cachorro x 15kg',
    costo: 4700,
    ganancia: 1180,
    precio: 5880,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Biopet Adulto Raza Pequeña x 15kg',
    costo: 4500,
    ganancia: 1130,
    precio: 5630,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Biopet Cachorro x 15kg',
    costo: 5250,
    ganancia: 1320,
    precio: 6570,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Biopet Perro Adulto x 20kg',
    costo: 5300,
    ganancia: 1330,
    precio: 6630,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Infinity Cachorro x 10kg',
    costo: 5300,
    ganancia: 1330,
    precio: 6630,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Infinity Perro pequeño x 15kg',
    costo: 5300,
    ganancia: 1330,
    precio: 6630,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Infinity Perro x 21kg',
    costo: 6380,
    ganancia: 1600,
    precio: 7980,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Infinity Gato x 10kg',
    costo: 5300,
    ganancia: 1330,
    precio: 6630,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Cari Amici Adulto x 20kg',
    costo: 4830,
    ganancia: 1210,
    precio: 6040,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Cari Amici Gato x 10kg',
    costo: 3770,
    ganancia: 950,
    precio: 4720,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: '9 Lives Gatitos x 8kg',
    costo: 4715,
    ganancia: 1185,
    precio: 5900,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: '9 lives Gato Adulto x 15kg Pescado/Carne',
    costo: 7650,
    ganancia: 1920,
    precio: 9570,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Vagoneta Perro Adulto x 20kg',
    costo: 4500,
    ganancia: 1130,
    precio: 5630,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Vagoneta Gato Adulto x 10kg',
    costo: 3550,
    ganancia: 890,
    precio: 4440,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Vagoneta Gato Adulto x 20kg',
    costo: 6750,
    ganancia: 1690,
    precio: 8440,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Dr Perrot Adulto x 22kg',
    costo: 4100,
    ganancia: 1030,
    precio: 5130,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Dr Perrot Adulto x 15kg',
    costo: 2900,
    ganancia: 850,
    precio: 3750,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Patriota Perro x 15kg',
    costo: 2200,
    ganancia: 850,
    precio: 3050,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Cooperacion Adulto x 15kg (CARNE / POLLO)',
    costo: 2870,
    ganancia: 850,
    precio: 3720,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Cooperacion Cachorro x 10kg',
    costo: 2470,
    ganancia: 850,
    precio: 3320,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Cooperacion Gato x 10kg (PESCADO / CARNE / POLLO)',
    costo: 2670,
    ganancia: 850,
    precio: 3520,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'KROFF Perro ADULTO X20KG',
    costo: 8800,
    ganancia: 2200,
    precio: 11000,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'KROFF Gato ADULTO X8 KG',
    costo: 6100,
    ganancia: 1530,
    precio: 7630,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Arroz Sr Dog x 15kg',
    costo: 1900,
    ganancia: 850,
    precio: 2750,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Arroz Tradicional Lumppy x 15kg',
    costo: 2600,
    ganancia: 850,
    precio: 3450,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Arroz Lumppy (CARNE ó POLLO) x 15kg',
    costo: 2760,
    ganancia: 850,
    precio: 3610,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Arroz Partido x 30kg',
    costo: 4250,
    ganancia: 1070,
    precio: 5320,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Alpiste x 10 kg',
    costo: 5650,
    ganancia: 1420,
    precio: 7070,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Alpiste x 30 kg',
    costo: 15600,
    ganancia: 3900,
    precio: 19500,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Mijo x 10 kg',
    costo: 2400,
    ganancia: 850,
    precio: 3250,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Canario x 10 kg',
    costo: 4450,
    ganancia: 1120,
    precio: 5570,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Cardenal x 10 kg',
    costo: 1900,
    ganancia: 850,
    precio: 2750,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Polenta x 25 kg',
    costo: 2950,
    ganancia: 850,
    precio: 3800,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Engorde x 25 kg',
    costo: 2860,
    ganancia: 850,
    precio: 3710,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Bebe Iniciador x 25kg',
    costo: 2860,
    ganancia: 850,
    precio: 3710,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Conejo Domestico x25 kg',
    costo: 2860,
    ganancia: 850,
    precio: 3710,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Ponedora Domestica x 25 kg',
    costo: 2800,
    ganancia: 850,
    precio: 3650,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Mezcla Gallina x 24kg, Lumppy',
    costo: 2350,
    ganancia: 850,
    precio: 3200,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Maíz Entero x 40KG, Lumppy',
    costo: 3500,
    ganancia: 880,
    precio: 4380,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Conejo x 25 kg (la Morocha)',
    costo: 2200,
    ganancia: 850,
    precio: 3050,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Avena Blanca x 30kg',
    costo: 2000,
    ganancia: 850,
    precio: 2850,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Mezcla Gallina Común x 24kg',
    costo: 1750,
    ganancia: 850,
    precio: 2600,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Maíz Entero x 30KG',
    costo: 1900,
    ganancia: 850,
    precio: 2750,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Girasol Confitero x 20kg',
    costo: 2300,
    ganancia: 850,
    precio: 3150,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Maíz Partido Grueso x 24kg',
    costo: 2100,
    ganancia: 850,
    precio: 2950,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Maíz Partido Fino x 24kg',
    costo: 2100,
    ganancia: 850,
    precio: 2950,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Pucherito x 15kg',
    costo: 1100,
    ganancia: 850,
    precio: 1950,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Pucherito x 8kg',
    costo: 1150,
    ganancia: 850,
    precio: 2000,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Conejo x 25 kg',
    costo: 2300,
    ganancia: 850,
    precio: 3150,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Bebe Iniciador x 25kg',
    costo: 2650,
    ganancia: 850,
    precio: 3500,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Ponedora x25kg',
    costo: 2420,
    ganancia: 850,
    precio: 3270,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'Engorde x 25kg',
    costo: 2420,
    ganancia: 850,
    precio: 3270,
    proveedor: 'BALANCEADOS',
  },
  {
    descripcionProducto: 'ROSCO PERRO CARNE X15',
    costo: 2970,
    ganancia: 850,
    precio: 3820,
    proveedor: 'GONZALEZ',
  },
  {
    descripcionProducto: 'ROSCO PERRO COCKTAIL x15',
    costo: 2700,
    ganancia: 850,
    precio: 3550,
    proveedor: 'GONZALEZ',
  },
  {
    descripcionProducto: 'DOG SELECTION CRIADORES ADULTO x21',
    costo: 5846,
    ganancia: 1464,
    precio: 7310,
    proveedor: 'GONZALEZ',
  },
  {
    descripcionProducto: 'ARROZ SABORIZADO GRAN CAMPEON x15',
    costo: 2540,
    ganancia: 850,
    precio: 3390,
    proveedor: 'GONZALEZ',
  },
  {
    descripcionProducto: 'PACHA ADULTO MIX x22',
    costo: 3970,
    ganancia: 1000,
    precio: 4970,
    proveedor: 'GONZALEZ',
  },
  {
    descripcionProducto: 'TIERNITOS ADULTO x22',
    costo: 5300,
    ganancia: 1330,
    precio: 6630,
    proveedor: 'GONZALEZ',
  },
  {
    descripcionProducto: 'CHACAL x22',
    costo: 3400,
    ganancia: 850,
    precio: 4250,
    proveedor: 'GONZALEZ',
  },
  {
    descripcionProducto: 'PROTEMIX ADULTO x21',
    costo: 6360,
    ganancia: 1590,
    precio: 7950,
    proveedor: 'GONZALEZ',
  },
  {
    descripcionProducto: 'CHACAL X15',
    costo: 2400,
    ganancia: 850,
    precio: 3250,
    proveedor: 'GONZALEZ',
  },
  {
    descripcionProducto: 'PACHA X15',
    costo: 2850,
    ganancia: 850,
    precio: 3700,
    proveedor: 'GONZALEZ',
  },
  {
    descripcionProducto: 'BALANCIN X15',
    costo: 2250,
    ganancia: 850,
    precio: 3100,
    proveedor: 'GONZALEZ',
  },
  {
    descripcionProducto: 'TRONQUITOS',
    costo: 2250,
    ganancia: 850,
    precio: 3100,
    proveedor: 'GONZALEZ',
  },
  {
    descripcionProducto: 'COMP POWER 2,5 A 5 KG',
    costo: 100,
    ganancia: 850,
    precio: 950,
    proveedor: 'POWER',
  },
  {
    descripcionProducto: 'COMP POWER 5 A 10 KG',
    costo: 100,
    ganancia: 850,
    precio: 950,
    proveedor: 'POWER',
  },
  {
    descripcionProducto: 'COMP POWER 10 A 20 KG',
    costo: 100,
    ganancia: 850,
    precio: 950,
    proveedor: 'POWER',
  },
  {
    descripcionProducto: 'COMP POWER 20 A 30 KG',
    costo: 100,
    ganancia: 850,
    precio: 950,
    proveedor: 'POWER',
  },
  {
    descripcionProducto: 'COMP POWER 30 A 40 KG',
    costo: 100,
    ganancia: 850,
    precio: 950,
    proveedor: 'POWER',
  },
  {
    descripcionProducto: 'OSSPRET GATO CHICO',
    costo: 100,
    ganancia: 850,
    precio: 950,
    proveedor: 'OSSPRET',
  },
  {
    descripcionProducto: 'OSSPRETGATO GRANDE',
    costo: 100,
    ganancia: 850,
    precio: 950,
    proveedor: 'OSSPRET',
  },
  {
    descripcionProducto: 'OSSPRET PERRO 2 A 10',
    costo: 100,
    ganancia: 850,
    precio: 950,
    proveedor: 'OSSPRET',
  },
  {
    descripcionProducto: 'OSSPRET DE 11 A 20',
    costo: 100,
    ganancia: 850,
    precio: 950,
    proveedor: 'OSSPRET',
  },
  {
    descripcionProducto: 'OSSPRET DE 21 A 40',
    costo: 100,
    ganancia: 850,
    precio: 950,
    proveedor: 'OSSPRET',
  },
  {
    descripcionProducto: 'OSSPRET DE 41 A 60',
    costo: 100,
    ganancia: 850,
    precio: 950,
    proveedor: 'OSSPRET',
  },
  {
    descripcionProducto: 'PIPETA POWER GATO CHICO',
    costo: 100,
    ganancia: 850,
    precio: 950,
    proveedor: 'POWER',
  },
  {
    descripcionProducto: 'PIPETA POWER GATO GRANDE',
    costo: 100,
    ganancia: 850,
    precio: 950,
    proveedor: 'POWER',
  },
  {
    descripcionProducto: 'PIPETA POWER PERRO 2 A 4 KG',
    costo: 100,
    ganancia: 850,
    precio: 950,
    proveedor: 'POWER',
  },
  {
    descripcionProducto: 'PIPETA POWER PERRO 5 A 10 KG',
    costo: 100,
    ganancia: 850,
    precio: 950,
    proveedor: 'POWER',
  },
  {
    descripcionProducto: 'PIPETA POWER PERRO 11 A 20 KG',
    costo: 100,
    ganancia: 850,
    precio: 950,
    proveedor: 'POWER',
  },
  {
    descripcionProducto: 'PIPETA POWER PERRO 21 A 40 KG',
    costo: 100,
    ganancia: 850,
    precio: 950,
    proveedor: 'POWER',
  },
  {
    descripcionProducto: 'PIPETA POWER PERRO 41 A 60 KG',
    costo: 100,
    ganancia: 850,
    precio: 950,
    proveedor: 'POWER',
  },
  {
    descripcionProducto: 'COMP SIMPARICA 2,5 A 5 KG',
    costo: 100,
    ganancia: 850,
    precio: 950,
    proveedor: 'SIMPARICA',
  },
  {
    descripcionProducto: 'COMP SIMPARICA 5 A 10 KG ',
    costo: 100,
    ganancia: 850,
    precio: 950,
    proveedor: 'SIMPARICA',
  },
  {
    descripcionProducto: 'COMP SIMPARICA DE 10 A 20 KG',
    costo: 100,
    ganancia: 850,
    precio: 950,
    proveedor: 'SIMPARICA',
  },
  {
    descripcionProducto: 'COMP SIMPARICA DE 20 A 40 KG',
    costo: 100,
    ganancia: 850,
    precio: 950,
    proveedor: 'SIMPARICA',
  },
  {
    descripcionProducto: 'COMP SIMPARICA DE 40 A 60',
    costo: 100,
    ganancia: 850,
    precio: 950,
    proveedor: 'SIMPARICA',
  },
  {
    descripcionProducto: 'COMP NEXGARD 5 A 10',
    costo: 100,
    ganancia: 850,
    precio: 950,
    proveedor: 'NEXGARD',
  },
  {
    descripcionProducto: 'PACHA COCKAIL X22',
    costo: 4230,
    ganancia: 1060,
    precio: 5290,
    proveedor: 'GONZALEZ',
  },
  {
    descripcionProducto: 'CAT SELECTION X10',
    costo: 4710,
    ganancia: 1180,
    precio: 5890,
    proveedor: 'GONZALEZ',
  },
  {
    descripcionProducto: 'ARROZ SABORIZADO IBISX15',
    costo: 2790,
    ganancia: 850,
    precio: 3640,
    proveedor: 'GONZALEZ',
  },
  {
    descripcionProducto: 'TIERNITOS CACHORRO X22',
    costo: 5950,
    ganancia: 1490,
    precio: 7440,
    proveedor: 'GONZALEZ',
  },
];
